"""added column on sponsor table

Revision ID: 1732a48071fd
Revises: a2668bc9da70
Create Date: 2025-11-05 15:08:48.857721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1732a48071fd'
down_revision = 'a2668bc9da70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors', 'name')
    # ### end Alembic commands ###
