"""updated sponsors  table

Revision ID: 18b74bd55a61
Revises: 526b21e69926
Create Date: 2025-11-07 14:00:47.435210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b74bd55a61'
down_revision = '526b21e69926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('sponsors', sa.Column('companylogo', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors', 'companylogo')
    op.drop_column('sponsors', 'category')
    # ### end Alembic commands ###
