"""added column on competitions  table

Revision ID: 526b21e69926
Revises: c855be9ffb87
Create Date: 2025-11-07 10:33:23.824832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526b21e69926'
down_revision = 'c855be9ffb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comps', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comps', 'title')
    # ### end Alembic commands ###
