"""initial database

Revision ID: a2668bc9da70
Revises: 
Create Date: 2025-11-05 15:03:50.894315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2668bc9da70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comps',
    sa.Column('compid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=225), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('compdetails', sa.String(length=255), nullable=True),
    sa.Column('appylink', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('compid')
    )
    op.create_table('sponsors',
    sa.Column('sponsorid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sponsoredtalents', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('linkedIn', sa.String(length=100), nullable=True),
    sa.Column('email_addres', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('sponsorid')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('students',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('dateofbirth', sa.DateTime(), nullable=True),
    sa.Column('gradelevel', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=50), nullable=True),
    sa.Column('picture', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('talents',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('talentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('talentname', sa.String(length=255), nullable=True),
    sa.Column('talentdetails', sa.String(length=500), nullable=True),
    sa.Column('talent_url', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('talentid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talents')
    op.drop_table('students')
    op.drop_table('users')
    op.drop_table('stories')
    op.drop_table('sponsors')
    op.drop_table('comps')
    # ### end Alembic commands ###
