"""added column on sponsor table

Revision ID: c855be9ffb87
Revises: 1732a48071fd
Create Date: 2025-11-06 16:41:52.034391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c855be9ffb87'
down_revision = '1732a48071fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('secretkey', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('adminid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
