"""the success table updated

Revision ID: caf3a4081653
Revises: 18b74bd55a61
Create Date: 2025-11-17 16:31:11.391737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf3a4081653'
down_revision = '18b74bd55a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'title')
    # ### end Alembic commands ###
